name: Deploy Lambda Function

on:
  push:
    paths:
      - "src/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install zip tool
        uses: montudor/action-zip@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4   # or @main / latest tag
        with:
          aws-region: eu-north-1
      
      - name: Create Zip file for Lambda Function
        run: cd src && zip -r code.zip .
      - name: AWS CLI v2
        uses: imehedi/actions-awscli-v2@latest
        with:
          #aws-region: eu-north-1
          args: "lambda update-function-code \
            --function-name arn:aws:lambda:us-east-1:281934898816:function:gitActionTest \
            --zip-file fileb://src/code.zip
            --aws-region eu-north-1"
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          #AWS_DEFAULT_REGION: "eu-north-1"
          AWS_REGION: eu-north-1

